version: '3.8'

services:
  db:
    image: postgres:16.2
    restart: always
    ports:
      - "5432:5432"
    networks:
      - logistics-network
    environment:
      POSTGRES_USER: logistics_app
      POSTGRES_PASSWORD: RFVcderfv
      POSTGRES_DB: logistics
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-h", "db" ]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 5s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: hesam-khorshidi/logistics-app:1.0
    ports:
      - "8080:8080"
    networks:
      - logistics-network
    depends_on:
       db:
         condition: service_healthy


networks:
  logistics-network:
    driver: bridge